import time
from constants import BORDER

def disgraced_knight_intro():
    print("So begins your journey Disgraced Knight.".center(70))
    time.sleep(3)
    print("It wasn't so long ago you knew glory.".center(70))
    time.sleep(3)
    print("But that time has passed.".center(70))
    time.sleep(3)
    print("There will be no praise from others on this voyage.".center(70))
    time.sleep(3)
    print("But regardless, do what you must to salvage what you can.".center(70))
    time.sleep(3)
    print("Good luck".center(70))
    time.sleep(3)
def expelled_scholar_intro():
    print("So begins your journey Expelled Scholar.".center(70))
    time.sleep(3)
    print("You did try your best.".center(70))
    time.sleep(3)
    print("But arrogance is a fools errand.".center(70))
    time.sleep(3)
    print("And this is your story now.".center(70))
    time.sleep(3)
    print("Go quickly. Before it's too late.".center(70))
    time.sleep(3)
    print("Good luck".center(70))
    time.sleep(3)

def fetid_brute_intro():
    print("The stench here is unbearable.".center(70))
    time.sleep(3)
    print("It's dark too.".center(70))
    time.sleep(5)
    print("Tortured roars fill the distance.".center(70))
    time.sleep(3)
    print("One gets louder.".center(70))
    time.sleep(3)
    print("This will be a battle indeed.".center(70))
    time.sleep(5)
def fetid_brute_outro():
    time.sleep(3)
    print("The brute is dead.".center(70))
    time.sleep(3)
    print("It's time to move on.".center(70))
    time.sleep(3)
    print("Another will take its place.".center(70))
    
def scalewing_alpha_intro():
    print("There is something in the sky.".center(70))
    time.sleep(3)
    print("It seems troubled.".center(70))
    time.sleep(3)
    print("Flying from its purpose.".center(70))
    time.sleep(3)
    print("Or toward it, perhaps.".center(70))
    time.sleep(3)
    print("Who really knows.".center(70))
    time.sleep(3)
def scalewing_alpha_outro():
    time.sleep(3)
    print("The scalewing is dead.".center(70))
    time.sleep(3)
    print("Eyes lifeless...".center(70))
    time.sleep(3)
    print("This changes nothing in the gray.".center(70))

def the_myth_intro():
    print("Voice: How many days have you been here?".rjust(70))
    time.sleep(3)
    print("...".rjust(70))
    time.sleep(3)
    print("Voice: I see...".rjust(70))
    time.sleep(3)
    print("Voice: you and I are not so different then.".rjust(70))
    time.sleep(3)
    print("Voice: let's not tarry on.".rjust(70))
    time.sleep(3)
def the_myth_outro():
    time.sleep(3)
    print("Voice: why do you persist?".rjust(70))
    time.sleep(3)
    print("Voice: do you even know?".rjust(70))
    time.sleep(3)

def unknown_intro():
    print("???: it's impressive to make it this far.".rjust(70))
    time.sleep(3)
    print("???: let me ask you a question.".rjust(70))
    time.sleep(3)
    print("???: are you ever unable to feel the present?".rjust(70))
    time.sleep(3)
    print("???: so much so that your mind dwells in memories alone?".rjust(70))
    time.sleep(3)
    print("???: is your mind even here at all?".rjust(70))
    time.sleep(3)
    print("???: let us find out.".rjust(70))
    time.sleep(5)
def unknown_outro():
    time.sleep(3)
    print("???: it appears I judged incorrectly.".rjust(70))
    time.sleep(3)
    print("???: until next time.".rjust(70))
    time.sleep(5)