import time
from constants import BORDER

# Level Text
def desolate_place_intro():
    print(BORDER)
    print("A DESOLATE PLACE".center(100))
    print(BORDER)
    time.sleep(3)
    print("The great peace saw this land green and vibrant. Then the darkness came.".center(100))
    print("Washing it all away.".center(100))
    print("Though there is life to be found in the gray if you look closely.".center(100))
    print(BORDER)
    time.sleep(7)
def abandoned_sanctuary_intro():
    print(BORDER)
    print("ABANDONED SANCTUARY".center(100))
    print(BORDER)
    time.sleep(3)
    print("This place was thought to be impregnable.".center(100))
    print("And would remain so to this day, had they not rebelled.".center(100))
    print("It is now a product of what was never meant to be.".center(100))
    print(BORDER)
    time.sleep(7)
def southern_desert_intro():
    print(BORDER)
    print("SOUTHERN DESERT".center(100))
    print(BORDER)
    time.sleep(3)
    print("Crossing these dunes affords no mercy to those traversing.".center(100))
    print("The sandstorms are unforgiving.".center(100))
    print("Do not look back. Lest you lose direction.".center(100))
    print(BORDER)
    time.sleep(7)
def longways_aqueduct_intro():
    print(BORDER)
    print("LONGWAYS AQUEDUCT".center(100))
    print(BORDER)
    time.sleep(3)
    print("It is dark here. And those melodic screams tempt.".center(100))
    print("But to join would darken the gray.".center(100))
    print("Though many believe otherwise.".center(100))
    print(BORDER)
    time.sleep(7)
def lostnorth_forest_intro():
    print(BORDER)
    print("LOSTNORTH FOREST".center(100))
    print(BORDER)
    time.sleep(3)
    print("The air is fresh here. The warmth, a rare pleasantry.".center(100))
    print("Worthy of a rest, perhaps.".center(100))
    print(BORDER)
    time.sleep(7)
def alenia_farmland_intro():
    print(BORDER)
    print("ALENIA FARMLAND".center(100))
    print(BORDER)
    time.sleep(3)
    print("This place feels familiar. Good soil.".center(100))
    print("A template for the great peace. Gray willing.".center(100))
    print(BORDER)
    time.sleep(7)
def mountain_pass_intro():
    print(BORDER)
    print("MOUNTAIN PASS".center(100))
    print(BORDER)
    time.sleep(3)
    print("It feels odd having one way to go.".center(100))
    print("Walls preventing deviation. No real choice to be made.".center(100))
    print(BORDER)
    time.sleep(7)
def mountain_ascent_intro():
    print(BORDER)
    print("MOUNTAIN ASCENT".center(100))
    print(BORDER)
    time.sleep(3)
def mountain_cliffs_intro():
    print(BORDER)
    print("MOUNTAIN CLIFFS".center(100))
    print(BORDER)
    time.sleep(3)

# Character Text
def disgraced_knight_intro():
    print("So begins your journey Disgraced Knight.".center(100))
    time.sleep(3)
    print("It wasn't so long ago you knew glory.".center(100))
    time.sleep(3)
    print("But that time has passed.".center(100))
    time.sleep(3)
    print("There will be no praise from others on this voyage.".center(100))
    time.sleep(3)
    print("But regardless, do what you must to salvage what you can.".center(100))
    time.sleep(3)
    print("Good luck".center(100))
    time.sleep(3)
def expelled_scholar_intro():
    print("So begins your journey Expelled Scholar.".center(100))
    time.sleep(3)
    print("You did try your best.".center(100))
    time.sleep(3)
    print("But arrogance is a fools errand.".center(100))
    time.sleep(3)
    print("And this is your story now.".center(100))
    time.sleep(3)
    print("Go quickly. Before it's too late.".center(100))
    time.sleep(3)
    print("Good luck".center(100))
    time.sleep(3)

# Boss Text
def fetid_brute_intro():
    print(BORDER)
    print("The stench here is unbearable.".center(100))
    time.sleep(3)
    print("It's dark too.".center(100))
    time.sleep(5)
    print("Tortured roars fill the distance.".center(100))
    time.sleep(3)
    print("One gets louder.".center(100))
    time.sleep(3)
    print("This will be a battle indeed.".center(100))
    print(BORDER)
    time.sleep(5)
def fetid_brute_outro():
    time.sleep(3)
    print(BORDER)
    print("The brute is dead.".center(100))
    time.sleep(3)
    print("It's time to move on.".center(100))
    time.sleep(3)
    print("Another will take its place.".center(100))
    print(BORDER)
    time.sleep(5)    
def scalewing_alpha_intro():
    print(BORDER)
    print("There is something in the sky.".center(100))
    time.sleep(3)
    print("It seems troubled.".center(100))
    time.sleep(3)
    print("Flying from its purpose.".center(100))
    time.sleep(3)
    print("Or toward it, perhaps.".center(100))
    time.sleep(3)
    print("Who really knows.".center(100))
    print(BORDER)
    time.sleep(3)
def scalewing_alpha_outro():
    time.sleep(3)
    print(BORDER)
    print("The scalewing is dead.".center(100))
    time.sleep(3)
    print("Eyes lifeless...".center(100))
    time.sleep(3)
    print("This changes nothing in the gray.".center(100))
    print(BORDER)
    time.sleep(5)
def the_myth_intro():
    print(BORDER)
    print("Voice: How many days have you been here?".rjust(100))
    time.sleep(3)
    print("...".rjust(100))
    time.sleep(3)
    print("Voice: I see...".rjust(100))
    time.sleep(3)
    print("Voice: you and I are not so different then.".rjust(100))
    time.sleep(3)
    print("Voice: let's not tarry on.".rjust(100))
    print(BORDER)
    time.sleep(3)
def the_myth_outro():
    time.sleep(3)
    print("Voice: why do you persist?".rjust(100))
    time.sleep(3)
    print("Voice: do you even know?".rjust(100))
    print(BORDER)
    time.sleep(5)
def unknown_intro():
    print(BORDER)
    print("???: it's impressive to make it this far.".rjust(100))
    time.sleep(3)
    print("???: let me ask you a question.".rjust(100))
    time.sleep(3)
    print("???: are you ever unable to feel the present?".rjust(100))
    time.sleep(3)
    print("???: so much so that your mind dwells in memories alone?".rjust(100))
    time.sleep(3)
    print("???: is your mind even here at all?".rjust(100))
    time.sleep(3)
    print("???: let us find out.".rjust(100))
    print(BORDER)
    time.sleep(5)
def unknown_outro():
    time.sleep(3)
    print(BORDER)
    print("???: it appears I judged incorrectly.".rjust(100))
    time.sleep(3)
    print("???: until we meet next".rjust(100))
    print(BORDER)
    time.sleep(5)